### ISSUE TITLE
hi ， a question about multi-gpu

### ISSUE THREAD

**Issue by jun0wanan** [vgaraujov/CPC-NLP-PyTorch#1]
Will this make  the result bad ?

**Comment by vgaraujov** [comment]
Hello

It shouldn't, the multiple gpu option allows you to use more batches during training

**Comment by jun0wanan** [comment]
> Hello
> 
> It shouldn't, the multiple gpu option allows you to use more batches during training

Thank you your reply . When I run your work  , I find this module did't have 


box_from_file
`from box import box_from_file
ModuleNotFoundError: No module named 'box'`

**Comment by jun0wanan** [comment]
> Hello
> 
> It shouldn't, the multiple gpu option allows you to use more batches during training

trained on 8 GPUs, each with a batch size of 64...

Hi , I want to run a batch size of 64 on 8gpus ,but not each with a batch size of 64, can I ? 
Thank you

**Comment by vgaraujov** [comment]
If I get it right, you want to use 8 GPUs with a batch size of 8 each. In that case, you need to set the `batch_size` parameter to 8 in the `config_cpc.yaml` file.

With that configuration, the model will have a different result because it will receive fewer negative samples.
